### ISSUE TITLE
Auth issue

### ISSUE THREAD

**Issue by Redcxx** [azuline/pixiv-api#2]
hey there, pixiv update its validation on the android. There is a discussion [here](https://github.com/upbit/pixivpy/issues/83) and it has been fixed by [this](https://github.com/DaRealFreak/pixivpy/commit/980c68b39a37743c0774b719e92e044977b146e0) commit. The reason is pixiv now checks `x-client-time` and `x-client-hash` according to the discussion so we need to add them in the headers like:
`'X-Client-Time': local_time,`
`'X-Client-Hash': hashlib.md5((local_time+self.hash_secret).encode('utf-8')).hexdigest(),`
where self.hash_secret is a constant: `'28c1fdd170a5204386cb1313c7077b34f83e4aaf4aa829ce78c231e05b0bae2c'`.
I have no idea where he found these so I can't provide more details ._.

**Comment by Redcxx** [comment]
Ah I forget to add `local_time` is `datetime.now().isoformat()`

**Comment by dazuling** [comment]
thanks, will fix!
