### ISSUE TITLE
Help about client id and secret

### ISSUE THREAD

**Issue by mibori** [azuline/pixiv-api#4]
You use `client_id='KzEZED7aC0vird8jWyHM38mXjNTY'` and `client_secret='W9JZoJe00qPvJsiyCGT3CCtC6ZUtdpKpzMbNlUGP'`. Could you help me how to create my own pair?

**Comment by azuline** [comment]
I don't believe Pixiv has an "official" user API or a location to generate client id's. The API this library uses is the API designed for the mobile applications, and this id/secret pair presumably come from those applications. Many other projects are also using this id/secret pair.
