### ISSUE TITLE
Offset issue with fetch_illustrations_following?

### ISSUE THREAD

**Issue by wcronai** [azuline/pixiv-api#8]
Tried to retrieve illustrations from followers but am only able to retrieve 30 illustrations and when I tried 

response = client.fetch_illustrations_following(Visibility.PUBLIC, offset=response['next']),

I only get the same 30 illustrations (the first 30) instead of the next 30 illustrations.

Could be an issue in the GET response where offset isn't passed as the params? Not sure or am I just using this fetch_illustrations_following wrongly?

**Comment by azuline** [comment]
Whoops! Thanks for the report, fixed in v0.3.5.
