### ISSUE TITLE
If you're still working on this project, I added Novel and Ugoira download support

### ISSUE THREAD

**Issue by Diamond-Frost** [azuline/pixiv-api#9]
After using this lib to make a pixiv downloader, I needed Novel and Ugoira support, so I added a Ugoira class, with download and create_gif method, and added a download method to the Novel class

I also added some methods to Client:
fetch_novel (returns a Novel class)
fetch_user_novels (returns a dict: {'novels': List[Novel], 'next': int | None}
fetch_ugoira (returns a Ugoira class)
fetch_novel_text (returns a dict)

I also made it, when an Illustration is of content-type "UGOIRA", it fetches the Ugoira metadata and downloads that

I intend to add Fanbox support as well

**Comment by azuline** [comment]
I am not working on it actively, but I am maintaining it. PRs welcome :-)

**Comment by azuline** [comment]
Closed due to inactivity.
